// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE_4oHpZsEc6pszKehczV9JLRBeSzyFsg',
    appId: '1:280168325934:web:3bddb1075bc9780edfd0bf',
    messagingSenderId: '280168325934',
    projectId: 'tecky-chat-23b7c',
    authDomain: 'tecky-chat-23b7c.firebaseapp.com',
    storageBucket: 'tecky-chat-23b7c.appspot.com',
    measurementId: 'G-RQMDL6QEX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpv1VT-BhN1gsKJ8eJXsGHl9OoFdU3aDQ',
    appId: '1:280168325934:android:3edaf8fd2d8120a0dfd0bf',
    messagingSenderId: '280168325934',
    projectId: 'tecky-chat-23b7c',
    storageBucket: 'tecky-chat-23b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA21Z5-WoVxoK7ExS4f-kSnROX0VOxpdJ4',
    appId: '1:280168325934:ios:84d2e6c0d0a8dfcadfd0bf',
    messagingSenderId: '280168325934',
    projectId: 'tecky-chat-23b7c',
    storageBucket: 'tecky-chat-23b7c.appspot.com',
    iosClientId: '280168325934-dei0kmag06si5ps7avohrf4v8tc5v4l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.teckyChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA21Z5-WoVxoK7ExS4f-kSnROX0VOxpdJ4',
    appId: '1:280168325934:ios:84d2e6c0d0a8dfcadfd0bf',
    messagingSenderId: '280168325934',
    projectId: 'tecky-chat-23b7c',
    storageBucket: 'tecky-chat-23b7c.appspot.com',
    iosClientId: '280168325934-dei0kmag06si5ps7avohrf4v8tc5v4l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.teckyChat',
  );
}
